version: "3.9"
services:
  mysql:
    # build:
    #   context: .
    image: cust-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Abcd1234
    volumes:
      - "./ssl/certs:/certs"
      - "./ssl/my.cnf:/etc/my.cnf"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080