version: "3.9"
services:
  mysql:
    build:
      context: mysql
      args:
        - progress=plain
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Abcd1234
    volumes:
      - "./certs:/certs"
      - "./mysqlResources/my.cnf:/etc/my.cnf"
      - "./mysqlResources/data:/var/lib/mysql"
      - "./mysqlResources/log:/var/log"
    networks:
      - mysql-network
  pma:
    build:
      context: phpMyAdmin
      args:
        - progress=plain
    restart: unless-stopped
    environment:
      - PMA_HOST=client.{{host}}
    volumes:
      - ./phpMyAdminResources/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./certs/ca-cert.pem:/etc/phpmyadmin/ca-cert.pem
      - ./certs/client-cert.pem:/etc/phpmyadmin/client-cert.pem
      - ./certs/client-key.pem:/etc/phpmyadmin/client-key.pem
    ports:
      - "8080:80"
    networks:
      - mysql-network
    links:
      - mysql:mysql.{{host}}
    depends_on:
      - mysql
networks:
  mysql-network:
    driver: bridge